// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6Sxs7Q1TezXMAHJlo_bD1VRhOUnv-Cs',
    appId: '1:333799394567:web:720ee636a23b61e97fc9a2',
    messagingSenderId: '333799394567',
    projectId: 'solulab2',
    authDomain: 'solulab2.firebaseapp.com',
    storageBucket: 'solulab2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB-tUqI2TRVjWFMFJod0IfLpLj5GmU-VE',
    appId: '1:333799394567:android:019107f218c189187fc9a2',
    messagingSenderId: '333799394567',
    projectId: 'solulab2',
    storageBucket: 'solulab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGe4f57msqcyNxiFtYJ2TGXsEcpEOz4_s',
    appId: '1:333799394567:ios:acb640b7554b53927fc9a2',
    messagingSenderId: '333799394567',
    projectId: 'solulab2',
    storageBucket: 'solulab2.appspot.com',
    iosBundleId: 'com.example.solulab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGe4f57msqcyNxiFtYJ2TGXsEcpEOz4_s',
    appId: '1:333799394567:ios:acb640b7554b53927fc9a2',
    messagingSenderId: '333799394567',
    projectId: 'solulab2',
    storageBucket: 'solulab2.appspot.com',
    iosBundleId: 'com.example.solulab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ6Sxs7Q1TezXMAHJlo_bD1VRhOUnv-Cs',
    appId: '1:333799394567:web:f42591be18397ae67fc9a2',
    messagingSenderId: '333799394567',
    projectId: 'solulab2',
    authDomain: 'solulab2.firebaseapp.com',
    storageBucket: 'solulab2.appspot.com',
  );
}
